# Configuration file for access via CloudCannon interface
global:
  site_url: 'https://www.velamagia.com.br'
  title: Cursos de Vela Oceânica - Velamagia
  tel: '+55 (47) 9 9204-1363'
  email: 'ola@velamagia.com.br'
  social:
    - icon: "Facebook"
      url: 'https://facebook.com'
    - icon: "Instagram"
      url: 'https://instagram.com'   
    - icon: "Messenger"
      url: 'https://messenger.com'
    - icon: "WhatsApp"
      url: 'https://wa.me/+5547992041363'
  preview_image:  
##### Fonts #####
fonts:
  google_fonts_embed_code_block: '<link href="https://fonts.googleapis.com/css2?family=Bitter:ital,wght@0,100;0,300;0,400;0,600;1,100;1,300;1,400;1,600&family=Questrial&display=swap" rel="stylesheet">' 
  body_font_family: "'Bitter', serif;"
  heading_font_family: "'Questrial', sans-serif;"

##### Site main colors #####
colors:
  dark_color: '#363636'
  light_color: 'whitesmoke'
  accent_color: '#003453'

##### Navigation menus and submenus #####
navigation:
  menus:
    - name: Início
      url: /
      dropdown: false
      submenus:
        - name:
          url:
    - name: Cursos
      url: 
      dropdown: true
      submenus:
        - name: Iniciante
          url: /cursos/iniciante
        - name: Aperfeiçoamento
          url: /cursos/aperfeicoamento
    - name: Passeios
      url:
      dropdown: true
      submenus:
        - name: Florianópolis
          url: /passeios/florianopolis
        - name: Balneário Camboriú
          url: /passeios/balneario-camboriu
        - name: Porto Belo
          url: /passeios/porto-belo
    - name: Contato
      url: /contato
      dropdown: false
      submenus:
        - name:
          url:  
seo:
  site_description_text: Here's the site description text
  keywords: ['vela oceânica', 'cursos de vela oceânica', 'passeios de barco em balneário camboriu']